# Generated by Django 2.2 on 2019-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('state', models.BooleanField()),
                ('type', models.CharField(max_length=1)),
                ('cluster', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
