# Generated by Django 2.2 on 2019-04-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='type',
            new_name='store_type',
        ),
    ]
