# Generated by Django 2.2 on 2019-04-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0002_auto_20190427_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
