# Generated by Django 2.2 on 2019-04-27 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0004_auto_20190427_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'HolidaysLocals',
            },
        ),
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'HolidayTypes',
            },
        ),
        migrations.CreateModel(
            name='HolidayEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=200)),
                ('transferred', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorita.City')),
                ('holiday_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorita.HolidayType')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorita.HolidayLocale')),
            ],
            options={
                'verbose_name_plural': 'HolidaysEvents',
            },
        ),
    ]
