# Generated by Django 2.2 on 2019-04-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0006_classitem_familyitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='class_item',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ClassItem',
        ),
    ]
