# Generated by Django 2.2 on 2019-04-27 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0007_auto_20190427_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('dcoilwtico', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Oils',
            },
        ),
    ]
