# Generated by Django 2.2 on 2019-04-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0008_oil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('basic_salary', models.FloatField(default=0)),
                ('extra_hour', models.FloatField(default=0)),
                ('night_weekend', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Salaries',
            },
        ),
    ]
