# Generated by Django 2.2 on 2019-04-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0009_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('num_trucks', models.IntegerField(default=0)),
                ('num_drivers', models.IntegerField(default=0)),
                ('num_refrigerator', models.IntegerField(default=0)),
                ('num_normal', models.IntegerField(default=0)),
                ('num_van', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Trucks',
            },
        ),
    ]
