# Generated by Django 2.2 on 2019-04-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0012_auto_20190427_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
