# Generated by Django 2.2 on 2019-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0014_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='onpromotion',
            field=models.BooleanField(default=False),
        ),
    ]
