# Generated by Django 2.2 on 2019-06-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0015_auto_20190428_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speed', models.IntegerField(default=0)),
                ('capacity', models.FloatField(default=1000)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Types',
            },
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorita.VehicleType'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorita.VehicleType'),
        ),
    ]
