# Generated by Django 2.2 on 2019-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0016_auto_20190623_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name_plural': 'VehicleTypes'},
        ),
        migrations.RemoveField(
            model_name='salary',
            name='year',
        ),
        migrations.AddField(
            model_name='salary',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='capacity',
            field=models.IntegerField(default=1000),
        ),
    ]
