# Generated by Django 2.2 on 2019-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0017_auto_20190623_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oil',
            name='dcoilwtico',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
