# Generated by Django 2.2 on 2019-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0019_auto_20190623_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oil',
            name='date',
            field=models.DateField(),
        ),
    ]
