# Generated by Django 2.2 on 2019-07-02 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import favorita.forms


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0023_auto_20190628_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'FuelTypes',
            },
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='driver_salary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='favorita.Salary'),
        ),
        migrations.AlterField(
            model_name='holidayevent',
            name='date',
            field=favorita.forms.MyDateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='route_date',
            field=favorita.forms.MyDateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oil',
            name='date',
            field=favorita.forms.MyDateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=favorita.forms.MyDateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=favorita.forms.MyDateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='fuel_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='favorita.FuelType'),
        ),
    ]
