# Generated by Django 2.2 on 2019-07-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0024_auto_20190702_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='basic_salary',
            new_name='normal_hour',
        ),
    ]
