# Generated by Django 2.2 on 2019-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0025_auto_20190702_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time_windows', models.FloatField(blank=True, default=0, null=True)),
                ('break_time', models.FloatField(blank=True, default=0, null=True)),
                ('load_unload_time', models.FloatField(blank=True, default=0, null=True)),
                ('full_time', models.FloatField(blank=True, default=0, null=True)),
                ('extra_time', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
