# Generated by Django 2.2 on 2019-07-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0026_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='km_per_galon',
            field=models.FloatField(default=0),
        ),
    ]
