# Generated by Django 2.2 on 2019-07-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0028_auto_20190704_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='cast_time_result',
            new_name='delivery_time_result',
        ),
    ]
