# Generated by Django 2.2 on 2019-07-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0029_auto_20190704_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='gasoline_cost_rate',
            new_name='fuel_cost_rate',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='gasoline_cost_result',
            new_name='fuel_cost_result',
        ),
    ]
