# Generated by Django 2.2 on 2019-07-09 22:27

from django.db import migrations, models
import django.db.models.deletion
import favorita.forms


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0030_auto_20190704_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletype',
            old_name='speed',
            new_name='max_speed_limit',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_type',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='driver_salary',
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_hour_cost',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='driver',
            name='max_work_extra_time',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='driver',
            name='max_work_time',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='max_work_time',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='delivery_time_rate',
            field=favorita.forms.MinMaxFloat(default=0.2),
        ),
        migrations.AlterField(
            model_name='log',
            name='distance_rate',
            field=favorita.forms.MinMaxFloat(default=0.2),
        ),
        migrations.AlterField(
            model_name='log',
            name='fuel_cost_rate',
            field=favorita.forms.MinMaxFloat(default=0.2),
        ),
        migrations.AlterField(
            model_name='log',
            name='num_trucks_rate',
            field=favorita.forms.MinMaxFloat(default=0.2),
        ),
        migrations.AlterField(
            model_name='log',
            name='staff_cost_rate',
            field=favorita.forms.MinMaxFloat(default=0.2),
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('vehicle_type', models.ManyToManyField(to='favorita.VehicleType')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='favorita.DriverLicense'),
        ),
    ]
