# Generated by Django 2.2.3 on 2019-07-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0032_auto_20190710_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='extra_time',
            new_name='drive_time_period',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='full_time',
            new_name='extra_hour_rate',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='work_time_windows',
            new_name='night_hour_rate',
        ),
    ]
