# Generated by Django 2.2.3 on 2019-07-13 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0033_auto_20190710_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='break_time',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='drive_time_period',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='load_unload_time',
        ),
        migrations.AddField(
            model_name='configuration',
            name='duration_break_time',
            field=models.TimeField(default=datetime.datetime(1994, 1, 31, 0, 15)),
        ),
        migrations.AddField(
            model_name='configuration',
            name='duration_driving_time',
            field=models.TimeField(default=datetime.datetime(1994, 1, 31, 2, 0)),
        ),
        migrations.AddField(
            model_name='configuration',
            name='duration_load_time',
            field=models.TimeField(default=datetime.datetime(1994, 1, 31, 0, 15)),
        ),
        migrations.AddField(
            model_name='item',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='close_hour',
            field=models.TimeField(default=datetime.datetime(1994, 1, 31, 22, 0)),
        ),
        migrations.AddField(
            model_name='store',
            name='open_hour',
            field=models.TimeField(default=datetime.datetime(1994, 1, 31, 6, 0)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='max_work_extra_time',
            field=models.TimeField(default=datetime.datetime(1994, 1, 31, 4, 0)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='max_work_time',
            field=models.TimeField(default=datetime.datetime(1994, 1, 31, 8, 0)),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='max_work_time',
            field=models.TimeField(default=datetime.datetime(1994, 1, 31, 18, 0)),
        ),
    ]
