# Generated by Django 2.2.3 on 2019-07-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0035_auto_20190718_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='parameter1',
            new_name='crossing_rate',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='parameter2',
            new_name='failed_attempts_stop',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='parameter3',
            new_name='mutation_rate',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='parameter4',
            new_name='number_iterations',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='parameter5',
            new_name='population_size',
        ),
        migrations.RemoveField(
            model_name='log',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='log',
            name='parameter6',
        ),
    ]
