# Generated by Django 2.2.3 on 2019-07-19 20:51

from django.db import migrations, models
import favorita.forms


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0036_auto_20190719_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='crossing_rate',
            field=favorita.forms.MinMaxFloat(default=0.5),
        ),
        migrations.AlterField(
            model_name='log',
            name='failed_attempts_stop',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='mutation_rate',
            field=favorita.forms.MinMaxFloat(default=0.5),
        ),
        migrations.AlterField(
            model_name='log',
            name='number_iterations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='population_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
