# Generated by Django 2.2.3 on 2019-08-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0038_auto_20190719_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
