# Generated by Django 2.2.3 on 2019-08-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0039_auto_20190801_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='delivery_time_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='distance_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='fuel_cost_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='num_trucks_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='staff_cost_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
