# Generated by Django 2.2.3 on 2019-08-18 11:09

import django.core.validators
from django.db import migrations, models
import favorita.forms


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0041_auto_20190813_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='delivery_time_rate',
        ),
        migrations.RemoveField(
            model_name='log',
            name='distance_rate',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fuel_cost_rate',
        ),
        migrations.RemoveField(
            model_name='log',
            name='num_trucks_rate',
        ),
        migrations.RemoveField(
            model_name='log',
            name='staff_cost_rate',
        ),
        migrations.AddField(
            model_name='log',
            name='delivery_time_weight',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.2, max_digits=18),
        ),
        migrations.AddField(
            model_name='log',
            name='distance_weight',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.2, max_digits=18),
        ),
        migrations.AddField(
            model_name='log',
            name='fuel_cost_weight',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.2, max_digits=18),
        ),
        migrations.AddField(
            model_name='log',
            name='num_trucks_weight',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.2, max_digits=18),
        ),
        migrations.AddField(
            model_name='log',
            name='staff_cost_weight',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='crossing_rate',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='mutation_rate',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='number_iterations',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='population_size',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='metalog',
            name='crossing_rate',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='metalog',
            name='mutation_rate',
            field=favorita.forms.MinMaxDecimal(decimal_places=2, default=0.5, max_digits=18),
        ),
    ]
