# Generated by Django 2.2.3 on 2019-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0042_auto_20190818_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='total_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
