# Generated by Django 2.2.3 on 2019-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0044_auto_20190820_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='avg_result',
            new_name='mean_result',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='media_result',
            new_name='median_result',
        ),
        migrations.RenameField(
            model_name='metalog',
            old_name='media_result',
            new_name='mean_result',
        ),
        migrations.RenameField(
            model_name='metalog',
            old_name='avg_result',
            new_name='median_result',
        ),
        migrations.AddField(
            model_name='log',
            name='variance_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='metalog',
            name='variance_result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
