# Generated by Django 2.2.3 on 2019-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0045_auto_20190820_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='max_iterations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='max_population',
            field=models.IntegerField(default=0),
        ),
    ]
