# Generated by Django 2.2.3 on 2019-08-23 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0046_auto_20190820_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalog',
            name='number_iterations',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='metalog',
            name='population_size',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='metalog',
            name='total_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
