# Generated by Django 2.2.3 on 2019-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0047_auto_20190824_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='extra_hour_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='weekend_hour_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_hour_cost',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='km_per_galon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
