# Generated by Django 2.2.3 on 2019-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorita', '0048_auto_20190825_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='extra_hour_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='weekend_hour_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_hour_cost',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metalog',
            name='best_fitness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='km_per_galon',
            field=models.FloatField(default=0),
        ),
    ]
