################  CONSTANTS  #######################

global DRIVERS
global VEHICLES
global POPULATION_SIZE
global EVOLUTION_ITERATIONS
global MUTATION_RATE
global CROSSOVER_RATE
global FAILED_ATTEMPTS_STOP
global CONFIGURATION
global CENTRAL_STORE
global IS_WEEKEND_HOLIDAY
global DRIVING_TIME
global BREAK_TIME
global LOAD_TIME
global POPULATION_SIZE_META
global EVOLUTION_ITERATIONS_META
global MUTATION_RATE_META
global CROSSOVER_RATE_META
global FAILED_ATTEMPTS_STOP_META
global DRIVER_LICENSE
R = 6373.0