from django.urls import path, re_path, include
from . import views
from .middleware.start_app import *
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^stores$', views.stores, name='stores'),
    re_path(r'^store/(?P<id>\d+)/$', views.store, name='store'),
    re_path(r'^delete_store/(?P<id>\d+)/$', views.delete_store, name='delete_store'),
    re_path(r'^items$', views.items, name='items'),
    re_path(r'^item/(?P<id>\d+)/$', views.item, name='item'),
    re_path(r'^delete_item/(?P<id>\d+)/$', views.delete_item, name='delete_item'),
    re_path(r'^transactions$', views.transactions, name='transactions'),
    re_path(r'^transaction/(?P<id>\d+)/$', views.transaction, name='transaction'),
    re_path(r'^delete_transaction/(?P<id>\d+)/$', views.delete_transaction, name='delete_transaction'),
    re_path(r'^resources$', views.resources, name='resources'),
    re_path(r'^resource/(?P<id>\d+)/$', views.resource, name='resource'),
    re_path(r'^delete_resource/(?P<id>\d+)/$', views.delete_resource, name='delete_resource'),
    re_path(r'^oils$', views.oils, name='oils'),
    re_path(r'^oil/(?P<id>\d+)/$', views.oil, name='oil'),
    re_path(r'^delete_oil/(?P<id>\d+)/$', views.delete_oil, name='delete_oil'),
    re_path(r'^cities$', views.cities, name='cities'),
    re_path(r'^city/(?P<id>\d+)/$', views.city, name='city'),
    re_path(r'^delete_city/(?P<id>\d+)/$', views.delete_city, name='delete_city'),
    re_path(r'^states$', views.states, name='states'),
    re_path(r'^state/(?P<id>\d+)/$', views.state, name='state'),
    re_path(r'^delete_state/(?P<id>\d+)/$', views.delete_state, name='delete_state'),
    re_path(r'^families$', views.families, name='families'),
    re_path(r'^family/(?P<id>\d+)/$', views.family, name='family'),
    re_path(r'^delete_family/(?P<id>\d+)/$', views.delete_family, name='delete_family'),
    re_path(r'^holidays$', views.holidays, name='holidays'),
    re_path(r'^holiday/(?P<id>\d+)/$', views.holiday, name='holiday'),
    re_path(r'^delete_holiday/(?P<id>\d+)/$', views.delete_holiday, name='delete_holiday'),
    re_path(r'^holidaysLocales$', views.holidaysLocales, name='holidaysLocales'),
    re_path(r'^holidayLocale/(?P<id>\d+)/$', views.holidayLocale, name='holidayLocale'),
    re_path(r'^delete_holidayLocale/(?P<id>\d+)/$', views.delete_holidayLocale, name='delete_holidayLocale'),
    re_path(r'^holidaysTypes$', views.holidaysTypes, name='holidaysTypes'),
    re_path(r'^holidayType/(?P<id>\d+)/$', views.holidayType, name='holidayType'),
    re_path(r'^delete_holidayType/(?P<id>\d+)/$', views.delete_holidayType, name='delete_holidayType'),
    re_path(r'^vehicleTypes$', views.vehicleTypes, name='vehicleTypes'),
    re_path(r'^vehicleType/(?P<id>\d+)/$', views.vehicleType, name='vehicleType'),
    re_path(r'^delete_vehicleType/(?P<id>\d+)/$', views.delete_vehicleType, name='delete_vehicleType'),
    re_path(r'^vehicles$', views.vehicles, name='vehicles'),
    re_path(r'^vehicle/(?P<id>\d+)/$', views.vehicle, name='vehicle'),
    re_path(r'^delete_vehicle/(?P<id>\d+)/$', views.delete_vehicle, name='delete_vehicle'),
    re_path(r'^drivers$', views.drivers, name='drivers'),
    re_path(r'^driver/(?P<id>\d+)/$', views.driver, name='driver'),
    re_path(r'^delete_driver/(?P<id>\d+)/$', views.delete_driver, name='delete_driver'),
    re_path(r'^fuelTypes$', views.fuelTypes, name='fuelTypes'),
    re_path(r'^fuelType/(?P<id>\d+)/$', views.fuelType, name='fuelType'),
    re_path(r'^delete_fuelType/(?P<id>\d+)/$', views.delete_fuelType, name='delete_fuelType'),
    re_path(r'^driverLicenses$', views.driverLicenses, name='driverLicenses'),
    re_path(r'^driverLicense/(?P<id>\d+)/$', views.driverLicense, name='driverLicense'),
    re_path(r'^delete_driverLicense/(?P<id>\d+)/$', views.delete_driverLicense, name='delete_driverLicense'),
    re_path(r'^config_evaluation/(?P<id>\d+)/$', views.configEvaluation, name='configuration'),
    re_path(r'^select_evaluation/(?P<id>\d+)/$', views.selectEvaluation, name='selectEvaluation'),
    re_path(r'^show_results$', views.showLog, name='show_results'),
    re_path(r'^show_meta_results$', views.showMetaLog, name='show_meta_results'),
    re_path(r'^config_route/(?P<id>\d+)/$', views.configRoute, name='config_route'),
    re_path(r'^show_map$', views.showMap, name='show_map'),
]

loadTransactionsData()
